services:
  snipsslu:
    container_name: snipslu
    command: python -u app.py 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5008:5000
      - 5678:5678 
    volumes:
      - .:/app
    entrypoint: [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "-m", "app",  "--wait-for-client", "--multiprocess", "-m", "flask", "run", "-h", "0.0.0.0", "-p", "5000" ]

